/*!
 * CustomWiggle 3.2.6
 * https://greensock.com
 *
 * @license Copyright 2008-2020, GreenSock. All rights reserved.
 * Subject to the terms at https://greensock.com/standard-license or for
 * Club GreenSock members, the agreement issued with that membership.
 * @author: Jack Doyle, jack@greensock.com
*/
var gsap,_coreInitted,createCustomEase,_getGSAP=function(){return gsap||"undefined"!=typeof window&&(gsap=window.gsap)&&gsap.registerPlugin&&gsap},_eases={easeOut:"M0,1,C0.7,1,0.6,0,1,0",easeInOut:"M0,0,C0.1,0,0.24,1,0.444,1,0.644,1,0.6,0,1,0",anticipate:"M0,0,C0,0.222,0.024,0.386,0,0.4,0.18,0.455,0.65,0.646,0.7,0.67,0.9,0.76,1,0.846,1,1",uniform:"M0,0,C0,0.95,0,1,0,1,0,1,1,1,1,1,1,1,1,0,1,0"},_linearEase=function(e){return e},_initCore=function(e){if(!_coreInitted&&(gsap=_getGSAP(),createCustomEase=gsap&&gsap.parseEase("_CE"))){for(var t in _eases)_eases[t]=createCustomEase("",_eases[t]);_coreInitted=1,_create("wiggle").config=function(e){return"object"==typeof e?_create("",e):_create("wiggle("+e+")",{wiggles:+e})}}},_parseEase=function(e,t){return"function"!=typeof e&&(e=gsap.parseEase(e)||createCustomEase("",e)),e.custom||!t?e:function(t){return 1-e(t)}},_bonusValidated=1,_create=function(e,t){_coreInitted||_initCore(1);var a,s,n,r,i,o,u,g,c,p=0|((t=t||{}).wiggles||10),_=1/p,f=_/2,l="anticipate"===t.type,d=_eases[t.type]||_eases.easeOut,m=_linearEase;if(_bonusValidated){if(l&&(m=d,d=_eases.easeOut),t.timingEase&&(m=_parseEase(t.timingEase)),t.amplitudeEase&&(d=_parseEase(t.amplitudeEase,!0)),g=[0,0,(o=m(f))/4,0,o/2,u=l?-d(f):d(f),o,u],"random"===t.type){for(g.length=4,a=m(_),s=2*Math.random()-1,c=2;c<p;c++)f=a,u=s,a=m(_*c),s=2*Math.random()-1,n=Math.atan2(s-g[g.length-3],a-g[g.length-4]),r=Math.cos(n)*_,i=Math.sin(n)*_,g.push(f-r,u-i,f,u,f+r,u+i);g.push(a,0,1,0)}else{for(c=1;c<p;c++)g.push(m(f+_/2),u),f+=_,u=(u>0?-1:1)*d(c*_),o=m(f),g.push(m(f-_/2),u,o,u);g.push(m(f+_/4),u,m(f+_/4),0,1,0)}for(c=g.length;--c>-1;)g[c]=~~(1e3*g[c])/1e3;return g[2]="C"+g[2],createCustomEase(e,"M"+g.join(","))}};export var CustomWiggle=function(){function e(e,t){this.ease=_create(e,t)}return e.create=function(e,t){return _create(e,t)},e.register=function(e){gsap=e,_initCore()},e}();_getGSAP()&&gsap.registerPlugin(CustomWiggle),CustomWiggle.version="3.2.6";export{CustomWiggle as default};