/*!
 * TextPlugin 3.2.6
 * https://greensock.com
 *
 * @license Copyright 2008-2020, GreenSock. All rights reserved.
 * Subject to the terms at https://greensock.com/standard-license or for
 * Club GreenSock members, the agreement issued with that membership.
 * @author: Jack Doyle, jack@greensock.com
*/
import{emojiSafeSplit,getText,splitInnerHTML}from"./utils/strings.js";var gsap,_tempDiv,_getGSAP=function(){return gsap||"undefined"!=typeof window&&(gsap=window.gsap)&&gsap.registerPlugin&&gsap};export var TextPlugin={version:"3.2.6",name:"text",init:function(e,i,t){var n,s,l,a,r,p,o,g,f=e.nodeName.toUpperCase(),u=this;if(u.svg=e.getBBox&&("TEXT"===f||"TSPAN"===f),!("innerHTML"in e)&&!u.svg)return!1;if(u.target=e,"object"!=typeof i&&(i={value:i}),"value"in i){for(u.delimiter=i.delimiter||"",l=splitInnerHTML(e,u.delimiter),_tempDiv||(_tempDiv=document.createElement("div")),_tempDiv.innerHTML=i.value,s=splitInnerHTML(_tempDiv,u.delimiter),u.from=t._from,u.from&&(f=l,l=s,s=f),u.hasClass=!(!i.newClass&&!i.oldClass),u.newClass=i.newClass,u.oldClass=i.oldClass,n=(f=l.length-s.length)<0?l:s,u.fillChar=i.fillChar||(i.padSpace?"&nbsp;":""),f<0&&(f=-f);--f>-1;)n.push(u.fillChar);if("diff"===i.type){for(a=0,r=[],p=[],o="",f=0;f<s.length;f++)(g=s[f])===l[f]?o+=g:(r[a]=o+g,p[a++]=o+l[f],o="");s=r,l=p,o&&(s.push(o),l.push(o))}i.speed&&t.duration(Math.min(.05/i.speed*n.length,i.maxDuration||9999)),this.original=l,this.text=s,this._props.push("text")}else u.text=u.original=[""]},render:function(e,i){e>1?e=1:e<0&&(e=0),i.from&&(e=1-e);var t,n,s,l=i.text,a=i.hasClass,r=i.newClass,p=i.oldClass,o=i.delimiter,g=i.target,f=i.fillChar,u=i.original,m=l.length,d=e*m+.5|0;a?(n=p&&d!==m,s=((t=r&&d)?"<span class='"+r+"'>":"")+l.slice(0,d).join(o)+(t?"</span>":"")+(n?"<span class='"+p+"'>":"")+o+u.slice(d).join(o)+(n?"</span>":"")):s=l.slice(0,d).join(o)+o+u.slice(d).join(o),i.svg?g.textContent=s:g.innerHTML="&nbsp;"===f&&~s.indexOf("  ")?s.split("  ").join("&nbsp;&nbsp;"):s}};TextPlugin.splitInnerHTML=splitInnerHTML,TextPlugin.emojiSafeSplit=emojiSafeSplit,TextPlugin.getText=getText,_getGSAP()&&gsap.registerPlugin(TextPlugin);export{TextPlugin as default};