/*!
 * VelocityTracker: 3.2.6
 * https://greensock.com
 *
 * Copyright 2008-2020, GreenSock. All rights reserved.
 * Subject to the terms at https://greensock.com/standard-license or for
 * Club GreenSock members, the agreement issued with that membership.
 * @author: Jack Doyle, jack@greensock.com
*/
var gsap,_coreInitted,_toArray,_getUnit,_first,_ticker,_time1,_time2,_getCache,_getGSAP=function(){return gsap||"undefined"!=typeof window&&(gsap=window.gsap)},_lookup={},_round=function(t){return Math.round(1e4*t)/1e4},_getID=function(t){return _getCache(t).id},_getByTarget=function(t){return _lookup[_getID("string"==typeof t?_toArray(t)[0]:t)]},_onTick=function(t){var r,e=_first;if(t-_time1>=.05)for(_time2=_time1,_time1=t;e;)((r=e.g(e.t,e.p))!==e.v1||t-e.t1>.2)&&(e.v2=e.v1,e.v1=r,e.t2=e.t1,e.t1=t),e=e._next},_types={deg:360,rad:2*Math.PI},_initCore=function(){(gsap=_getGSAP())&&(_toArray=gsap.utils.toArray,_getUnit=gsap.utils.getUnit,_getCache=gsap.core.getCache,_ticker=gsap.ticker,_coreInitted=1)},PropTracker=function(t,r,e,i){this.t=t,this.p=r,this.g=t._gsap.get,this.rCap=_types[e||_getUnit(this.g(t,r))],this.v1=this.v2=0,this.t1=this.t2=_ticker.time,i&&(this._next=i,i._prev=this)};export var VelocityTracker=function(){function t(t,r){_coreInitted||_initCore(),this.target=_toArray(t)[0],_lookup[_getID(this.target)]=this,this._props={},r&&this.add(r)}t.register=function(t){gsap=t,_initCore()};var r=t.prototype;return r.get=function(t,r){var e,i,n=this._props[t];return e=parseFloat(r?n.v1:n.g(n.t,n.p))-parseFloat(n.v2),(i=n.rCap)&&(e%=i)!==e%(i/2)&&(e=e<0?e+i:e-i),_round(e/((r?n.t1:_ticker.time)-n.t2))},r.getAll=function(){var t,r={},e=this._props;for(t in e)r[t]=this.get(t);return r},r.isTracking=function(t){return t in this._props},r.add=function(t,r){t in this._props||(_first||(_ticker.add(_onTick),_time1=_time2=_ticker.time),_first=this._props[t]=new PropTracker(this.target,t,r,_first))},r.remove=function(t){var r,e,i=this._props[t];i&&(r=i._prev,e=i._next,r&&(r._next=e),e?e._prev=r:_first===i&&(_ticker.remove(_onTick),_first=0),delete this._props[t])},r.kill=function(t){for(var r in this._props)this.remove(r);t||delete _lookup[_getID(this.target)]},t.track=function(r,e,i){_coreInitted||_initCore();for(var n,o,_=[],a=_toArray(r),s=e.split(","),g=(i||"").split(","),c=a.length;c--;){for(n=_getByTarget(a[c])||new t(a[c]),o=s.length;o--;)n.add(s[o],g[o]||g[0]);_.push(n)}return _},t.untrack=function(t,r){var e=(r||"").split(",");_toArray(t).forEach((function(t){var r=_getByTarget(t);r&&(e.length?e.forEach((function(t){return r.remove(t)})):r.kill(1))}))},t.isTracking=function(t,r){var e=_getByTarget(t);return e&&e.isTracking(r)},t.getVelocity=function(t,r){var e=_getByTarget(t);return e&&e.isTracking(r)?e.get(r):void 0},t}();VelocityTracker.getByTarget=_getByTarget,_getGSAP()&&gsap.registerPlugin(VelocityTracker);export{VelocityTracker as default};